/*
CREATE DATABASE CAT_PROD;
USE CAT_PROD;
CREATE USER 'USRCATPROD'@'localhost' IDENTIFIED BY 'USRCATPROD123';
GRANT ALL PRIVILEGES ON CAT_PROD.* TO 'USRCATPROD'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
*/

/*DROP TABLE IF EXISTS CAT_PROD.CATDEPART;*/
  CREATE TABLE CAT_PROD.CATDEPART (
	ID INT(11)    NOT NULL,
	NOMBRE VARCHAR(50)   NOT NULL , 
	DESCR VARCHAR(50)   NOT NULL ,
        FOTO LONGBLOB NULL,
        PATH VARCHAR(255)   NOT NULL ,
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
        START_DATE TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL ,
	LAST_UPDATE_USER VARCHAR(50)   ,
        DEL_LOGIC INT(2)    NOT NULL,
	PRIMARY KEY (ID)
  ) ENGINE=INNODB;

/*DROP TABLE IF EXISTS CAT_PROD.CATCATEGOR;*/
  CREATE TABLE CAT_PROD.CATCATEGOR (
	ID INT(11)    NOT NULL,
	ID_DEPA INT(11)    NOT NULL,
	NOMBRE VARCHAR(100)   NOT NULL , 
	DESCR VARCHAR(255)   NOT NULL , 
        FOTO LONGBLOB NULL,
        PATH VARCHAR(255)   NOT NULL ,
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL ,
        START_DATE TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL ,
	LAST_UPDATE_USER VARCHAR(50)  ,
        DEL_LOGIC INT(2)    NOT NULL,
	PRIMARY KEY (ID) 
  ) ENGINE=INNODB;
alter table CAT_PROD.CATCATEGOR add foreign key(ID_DEPA) references CAT_PROD.CATDEPART (ID);

/*DROP TABLE IF EXISTS CAT_PROD.CATPROD;*/
CREATE TABLE CAT_PROD.CATPROD ( 
	ID INT(11)    NOT NULL,
	ID_CATEG INT(11)    NOT NULL,
	NOMBRE VARCHAR(100)   NOT NULL , 
	DESCR VARCHAR(255)   NOT NULL ,
        FOTO LONGBLOB NULL,
        PATH VARCHAR(255)   NOT NULL ,
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
        START_DATE TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL ,
	LAST_UPDATE_USER VARCHAR(50)   ,
        DEL_LOGIC INT(2)    NOT NULL,
	PRIMARY KEY (ID)
  ) ENGINE=INNODB;
  alter table CAT_PROD.CATPROD add foreign key(ID_CATEG) references CAT_PROD.CATCATEGOR (ID);

  /*DROP TABLE IF EXISTS CAT_PROD.CATSUBPROD;*/
CREATE TABLE CAT_PROD.CATSUBPROD (
	ID INT(11)    NOT NULL,
	ID_PROD INT(11)    NOT NULL,
	NOMBRE VARCHAR(100)   NOT NULL , 
	DESCR VARCHAR(255)   NOT NULL , 
        FOTO LONGBLOB NULL,
        PATH VARCHAR(255)   NOT NULL ,
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
        START_DATE TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL ,
	LAST_UPDATE_USER VARCHAR(50)   ,
        DEL_LOGIC INT(2)    NOT NULL,
	PRIMARY KEY (ID)
  ) ENGINE=INNODB;
  alter table CAT_PROD.CATSUBPROD add foreign key(ID_PROD) references CAT_PROD.CATPROD (ID_PROD);
  
  /*DROP TABLE IF EXISTS CAT_PROD.CATSUBPRODDET;*/
CREATE TABLE CAT_PROD.CATSUBPRODDET (
	ID INT(11) AUTO_INCREMENT  NOT NULL,
	ID_SUBPROD INT(11)    NOT NULL,
	NOMBRE VARCHAR(100)   NOT NULL , 
	DESCR VARCHAR(255)   NOT NULL , 
	STATUS_FLAG INT(2)    NOT NULL , 
	EXPIRY_DT TIMESTAMP   NOT NULL , 
	LAST_UPDATE_DT TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL , 
        START_DATE TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL ,
	LAST_UPDATE_USER VARCHAR(50)   ,
        DEL_LOGIC INT(2)    NOT NULL,
	PRIMARY KEY (ID)
  ) ENGINE=INNODB;
  alter table CAT_PROD.CATSUBPRODDET add foreign key(ID_SUBPROD) references CAT_PROD.CATSUBPROD (ID);
  ------------------------------------------------------------------------------------------------------------------

/*
DROP DATABASE ECOMM_SHOP;
DROP USER 'ECOMM_SHOP'@'localhost';
set foreign_key_checks=0;
DROP TABLE ECOMM_SHOP.CATROLES;
DROP TABLE ECOMM_SHOP.CATPAGO;
DROP TABLE ECOMM_SHOP.CATDESARROLLO;
DROP TABLE ECOMM_SHOP.CATLENGUAJE;
DROP TABLE ECOMM_SHOP.CATMONEDA;
DROP TABLE ECOMM_SHOP.CATCATEGORIA;
DROP TABLE ECOMM_SHOP.CATCALIFICACION;
DROP TABLE ECOMM_SHOP.CATCUENTA;
DROP TABLE ECOMM_SHOP.CATSUBCATEGORIA;
DROP TABLE ECOMM_SHOP.CATPRODUCTO;
DROP TABLE ECOMM_SHOP.CUENTAPRODUCTO;
DROP TABLE ECOMM_SHOP.USUARIO_ALIAS;
DROP TABLE ECOMM_SHOP.USUARIO_DIRECCION;
DROP TABLE ECOMM_SHOP.USUARIO_PERSONA;
DROP TABLE ECOMM_SHOP.METODO_PAGO;
DROP TABLE ECOMM_SHOP.MIS_DESARROLLOS;
DROP TABLE ECOMM_SHOP.MIS_CALIFICACIONES;
DROP TABLE ECOMM_SHOP.MI_CUENTA;
DROP TABLE ECOMM_SHOP.DETALLE_DESARROLLOS;
set foreign_key_checks=1;
*/